- name: create directory tree
  file: 
    path: /opt/splunk/etc/apps/{{ item }}
    state: directory
    owner: splunk
    group: splunk
    mode: 0755
    recurse: yes
  with_items:
    - cdm_all_indexer_base/local/
    - cdm_all_indexer_base/metadata/
    - cdm_all_indexes/local/
    - cdm_all_indexes/metadata/
    - cdm_full_license_server/local/
    - cdm_full_license_server/metadata/
    - cdm_indexer_volume_indexes/local/
    - cdm_indexer_volume_indexes/metadata/

- name: create base configurations
  template:
    src: '{{ item }}'
    dest: /opt/splunk/etc/apps/cdm_indexer_volume_indexes/local/{{ item | basename | regex_replace('\.j2','') }}
    group: splunk
    owner: splunk
    mode: 0755 
  with_fileglob:
    - /etc/ansible/roles/indexers/templates/cdm_indexer_volume_indexes/local/*

- name: create base configurations
  template:
    src: '{{ item }}'
    dest: /opt/splunk/etc/apps/cdm_indexer_volume_indexes/metadata/{{ item | basename | regex_replace('\.j2','') }}
    group: splunk
    owner: splunk
    mode: 0755 
  with_fileglob:
    - /etc/ansible/roles/indexers/templates/cdm_indexer_volume_indexes/metadata/*

- name: create base configurations
  template:
    src: '{{ item }}'
    dest: /opt/splunk/etc/apps/cdm_full_license_server/local/{{ item | basename | regex_replace('\.j2','') }}
    group: splunk
    owner: splunk
    mode: 0755 
  with_fileglob:
    - /etc/ansible/roles/indexers/templates/cdm_full_license_server/local/*

- name: create base configurations
  template:
    src: '{{ item }}'
    dest: /opt/splunk/etc/apps/cdm_full_license_server/metadata/{{ item | basename | regex_replace('\.j2','') }}
    group: splunk
    owner: splunk
    mode: 0755 
  with_fileglob:
    - /etc/ansible/roles/indexers/templates/cdm_full_license_server/metadata/*

- name: create base configurations
  template: 
    src: '{{ item }}' 
    dest: /opt/splunk/etc/apps/cdm_all_indexes/local/{{ item | basename | regex_replace('\.j2','') }}
    group: splunk
    owner: splunk
    mode: 0755 
  with_fileglob:
    - /etc/ansible/roles/indexers/templates/cdm_all_indexes/local/*

- name: create base configurations
  template: 
    src: '{{ item }}'
    dest: /opt/splunk/etc/apps/cdm_all_indexes/metadata/{{ item | basename | regex_replace('\.j2','') }}
    group: splunk
    owner: splunk
    mode: 0755 
  with_fileglob:
    - /etc/ansible/roles/indexers/templates/cdm_all_indexes/metadata/*

- name: create base configurations
  template: 
    src: '{{ item }}' 
    dest: /opt/splunk/etc/apps/cdm_all_indexer_base/local/{{ item | basename | regex_replace('\.j2','') }}
    group: splunk
    owner: splunk
    mode: 0755
  with_fileglob:
    - /etc/ansible/roles/indexers/templates/cdm_all_indexer_base/local/*

- name: create base configurations
  template: 
    src: '{{ item }}' 
    dest: /opt/splunk/etc/apps/cdm_all_indexer_base/metadata/{{ item | basename | regex_replace('\.j2','') }}
    group: splunk
    owner: splunk
    mode: 0755 
  with_fileglob:
    - /etc/ansible/roles/indexers/templates/cdm_all_indexer_base/metadata/*

