- name: install splunk
  yum:
    name: /tmp/splunk-6.5.3-36937ad027d4-linux-2.6-x86_64.rpm
    state: present

- name: accept splunk license
  command: "/opt/splunk/bin/splunk start --accept-license --answer-yes --no-prompt"
  become: yes
  become_method: sudo
  become_user: splunk
  ignore_errors: yes

- name: enable boot-start splunk service
  command: "/opt/splunk/bin/splunk enable boot-start -user splunk"
  ignore_errors: yes
