- name: create deployment client directories
  file: 
    path: /opt/splunk/etc/apps/{{ item }}
    state: directory
    owner: splunk
    group: splunk
    mode: 0755
    recurse: yes
  with_items:
    - cdm_all_deploymentclient/local/
    - cdm_all_deploymentclient/metadata/

- name: Populating local directory with template
  template:
    src: '{{ item }}' 
    dest: /opt/splunk/etc/apps/cdm_all_deploymentclient/local/{{ item | basename | regex_replace('\.j2','') }}
    group: splunk
    owner: splunk
    mode: 0755
  with_fileglob:
    - /etc/ansible/roles/deployment_clients/templates/cdm_all_deploymentclient/local/*

- name: populating metadata directory with template
  template: 
    src: '{{ item }}' 
    dest: /opt/splunk/etc/apps/cdm_all_deploymentclient/metadata/{{ item | basename | regex_replace('\.j2','') }}
    group: splunk
    owner: splunk
    mode: 0755
  with_fileglob:
    - /etc/ansible/roles/deployment_clients/templates/cdm_all_deploymentclient/metadata/*