---
- name: adding deployment apps and setting up serverclasses
  hosts: 
    - deployment_servers
  connection: ssh
  gather_facts: no
  vars_files:
    - /etc/ansible/vars/base_vars.yml
  roles:
    - deployment_servers

- name: restarting splunk on all instances
  hosts:
    - deployment_servers
  connection: ssh
  gather_facts: no
  roles:
    - restart_splunk
