---
- name: enforceing deployment_client app
  hosts:
    - deployment_clients
  connection: ssh
  gather_facts: no
  vars_files:
    - /etc/ansible/vars/deployment_client_vars.yml
  roles:
    - deployment_clients

- hosts: deployment_servers
  connection: ssh
  gather_facts: no
  vars_files:
    - /etc/ansible/vars/deployment_client_vars.yml
  tasks:

    - name: stats of directory
      stat:
        path: /opt/{{ splunk_instance }}/
      register: results
#      with_items:
#        - 
#        - etc/
#       - etc/apps/
#        - etc/apps/alert_logevent
#        - etc/apps/alert_webhook
#        - etc/apps/appsbrowser
#        - etc/apps/framework
#        - etc/apps/gettingstarted
#        - etc/apps/introspection_generator_addon
#        - etc/apps/launcher
#        - etc/apps/learned
#        - etc/apps/legacy
#        - etc/apps/sample_app
#        - etc/apps/search
#        - etc/apps/splunk_archiver
#        - etc/apps/SplunkForwarder
#        - etc/apps/splunk_httpinput
#        - etc/apps/splunk_instrumentation
#        - etc/apps/SplunkLightForwarder
#        - etc/apps/splunk_monitoring_console
#        - etc/apps/user-prefs
    
    - name: ensure ownership and permissions for splunk directories
      file: 
        path: /opt/{{ splunk_instance }}/
        state: directory
        owner: splunk
        group: splunk
        mode: 0755
        recurse: yes
      when: results.stat.gr_name != 'splunk'

    - name: enable boot-start splunk service
      command: "/opt/splunk/bin/splunk enable boot-start -user splunk"
      ignore_errors: yes

#### testing ######

#
#    - name: changeing logfile to dynamically add date and hostname
#      command: mv /var/log/ansible/ansiblelog.log /var/log/ansible/ansible_{{ lookup('pipe', 'date +%Y%m%d-%H:%M:%S')}}.log
