---
- name: enforceing deployment_client app
  hosts:
    - deployment_clients
  connection: ssh
  gather_facts: no
  vars_files:
    - /etc/ansible/vars/deployment_client_vars.yml
  roles:
    - deployment_clients

- hosts: deployment_clients
  connection: ssh
  gather_facts: no
  vars_files:
    - /etc/ansible/vars/deployment_client_vars.yml
  tasks:

    - name: "Create custom fact directory"
      file:
        path: "/etc/ansible/facts.d"
        state: "directory"

    - name: "Insert custom fact file"
      copy:
        src: /etc/ansible/files/file_owner.fact
        dest: /etc/ansible/facts.d/file_owner.fact
        mode: 0755

    - name: ensure ownership and permissions for splunk directories
      file: 
        path: /opt/{{ splunk_instance }}/
        state: directory
        owner: splunk
        group: splunk
        mode: 0755
        recurse: yes
      when: '{{ ansible_local.file_owner.file_owner }}' != 'splunk:splunk'

    - name: enable boot-start splunk service
      command: "/opt/splunk/bin/splunk enable boot-start -user splunk"
      ignore_errors: yes


#### testing ######

#    - name: stats of directory
#      stat:
#        path: /opt/{{ splunk_instance }}/
#      register: results
#    

#      when: results.stat.gr_name != 'splunk'

#    - name: changeing logfile to dynamically add date and hostname
#      command: mv /var/log/ansible/ansiblelog.log /var/log/ansible/ansible_{{ lookup('pipe', 'date +%Y%m%d-%H:%M:%S')}}.log
