---
- name: enforceing deployment_client app
  hosts:
    - deployment_clients
  connection: ssh
  gather_facts: no
  vars_files:
    - /etc/ansible/vars/deployment_client_vars.yml
  roles:
    - deployment_clients
    - enforcement
