---
#### Base apps git pull ####
- hosts: universal_forwarders
  connection: ssh
  gather_facts: no

  tasks:
    - name: Git pull for base apps
      git:
        repo: git@github.boozallencsn.com:yepez-alejandro/All_in_one_deployment.git
        dest: /opt/splunk/etc/apps/

    - name: change permissions on new apps
      file:
        path: /opt/splunk/etc/apps/
        mode: 755
        recurse: yes
        owner: splunk
        group: splunk
        state: directory
