---
#### Base apps git pull ####
- hosts: universal_forwarders
  connection: ssh
  gather_facts: no
  
  vars_files:
  - /etc/ansible/vars/base_vars.yml 

  tasks:
    - name: Git pull for base apps
      git:
        repo: git@github.boozallencsn.com:yepez-alejandro/All_in_one_deployment.git
        accept_hostkey: yes
        dest: /tmp/git/

    - name: copy apps from tmp to apps
      shell: cd /tmp/git/ && cp -r cdm_* /opt/splunk/etc/apps/
      args:
        executable: /bin/bash

    - name: change permissions on new apps
      file:
        path: /opt/splunk/etc/apps/
        mode: 0755
        recurse: yes
        owner: splunk
        group: splunk
        state: directory
