- name: testing our file tree
  find:
    paths: /opt/splunk/
    recurse: yes



#- name: create directory tree
#  file: 
#    path: /opt/splunk/etc/apps/{{ item }}
#    state: directory
#    owner: splunk
#    group: splunk
#    mode: 0755
#    recurse: yes
#  with_items:
#    - cdm_all_indexes/*

#- name: create base configurations
#  template: 
#    src: '{{ item }}' 
#    dest: /opt/splunk/etc/apps/cdm_all_indexes/local/{{ item | basename | regex_replace('\.j2','') }}
#    group: splunk
#    owner: splunk
#    mode: 0755 
#  with_fileglob:
#    - /etc/ansible/files/cdm_all_indexes/local/*

#- name: create base configurations
#  template: 
#    src: '{{ item }}'
#    dest: /opt/splunk/etc/apps/cdm_all_indexes/metadata/{{ item | basename | regex_replace('\.j2','') }}
#    group: splunk
#    owner: splunk
#    mode: 0755 
#  with_fileglob:
#    - /etc/ansible/files/cdm_all_indexes/metadata/*