- name: install wget and bzip2
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - wget
    - bzip2

- name: install parallel
  get_url:
    url: https://ftpmirror.gnu.org/parallel/parallel-20180122.tar.bz2
    dest: /etc/parallel-20180122.tar.bz2

- name: unpackage bizp2
  command: "bzip2 -dc /etc/parallel-20180122.tar.bz2"

- name: unpackage tar
  unarchive: 
    src: /etc/parallel-20180122.tar
    dest: /etc/

- name: changing directory to /etc/
  command: cd /etc/parallel-20180122

- name: unpackage parallel
  command: "./configure && make && sudo make install"

#- name: create directory tree
#  file: 
#    path: /opt/splunk/etc/apps/{{ item }}
#    state: directory
#    owner: splunk
#    group: splunk
#    mode: 0755
#    recurse: yes
#  with_items:
#    - cdm_all_indexes/*

#- name: create base configurations
#  template: 
#    src: '{{ item }}' 
#    dest: /opt/splunk/etc/apps/cdm_all_indexes/local/{{ item | basename | regex_replace('\.j2','') }}
#    group: splunk
#    owner: splunk
#    mode: 0755 
#  with_fileglob:
#    - /etc/ansible/files/cdm_all_indexes/local/*

#- name: create base configurations
#  template: 
#    src: '{{ item }}'
#    dest: /opt/splunk/etc/apps/cdm_all_indexes/metadata/{{ item | basename | regex_replace('\.j2','') }}
#    group: splunk
#    owner: splunk
#    mode: 0755 
#  with_fileglob:
#    - /etc/ansible/files/cdm_all_indexes/metadata/*